import streamlit as st
import requests
from PIL import Image
import io
import base64
import plotly.express as px
from pdf_report import generate_pdf_report

st.set_page_config(
    page_title="PhytoVision AI | Plant Pathology Diagnostic Engine",
    page_icon="🌿",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Sidebar
with st.sidebar:
    st.markdown("## 🌿 **PhytoVision AI**")
    st.caption("Deep Learning Plant Pathology & Explainability Engine")
    st.divider()

    st.markdown("### 📋 Supported Pathologies")
    st.markdown("""
    * **Angular Leaf Spot** (*Phaeoisariopsis*)
    * **Bean Rust** (*Uromyces*)
    * **Healthy Foliage**
    """)
    st.divider()

    st.markdown("### 📸 Image Capture Guidelines")
    st.markdown("""
    - Ensure single leaf fills 70% of frame.
    - Avoid direct sunlight reflections/glare.
    - Use neutral, uniform background.
    - Supported formats: `.jpg`, `.jpeg`, `.png` (Max 10MB).
    """)
    st.divider()

    st.warning("⚠️ **Agronomic Disclaimer**: Predictions are informational and generated by deep learning models. Always consult a certified agronomy extension specialist before high-scale chemical intervention.")
    api_endpoint = st.text_input("FastAPI Endpoint", value="http://127.0.0.1:8000/diagnose")

# Main Title
st.title("🌿 PhytoVision AI: Plant Pathology Diagnostic & Advisory Platform")
st.markdown("Upload foliar photographs for real-time disease detection, Grad-CAM attention mapping, and tiered remediation advice.")

# Upload Area & Validation
uploaded_file = st.file_uploader("Upload Leaf Specimen", type=["jpg", "jpeg", "png"])

col_left, col_right = st.columns([1, 1.2], gap="large")

with col_left:
    if uploaded_file is not None:
        if uploaded_file.size > 10 * 1024 * 1024:
            st.error("❌ File size exceeds 10MB limit. Please upload an optimized image.")
        else:
            image = Image.open(uploaded_file).convert("RGB")
            st.image(image, caption="Uploaded Leaf Specimen", use_container_width=True)
            diagnose_btn = st.button("🚀 Diagnose & Generate Heatmap", use_container_width=True)
    else:
        st.info("👆 Upload a leaf photograph above to begin analysis.")
        diagnose_btn = False

with col_right:
    if uploaded_file and diagnose_btn:
        with st.spinner("🔬 Computing activations & generating Grad-CAM localization..."):
            try:
                img_byte_arr = io.BytesIO()
                image.save(img_byte_arr, format="JPEG")
                img_bytes = img_byte_arr.getvalue()

                files = {"file": ("leaf.jpg", img_bytes, "image/jpeg")}
                response = requests.post(api_endpoint, files=files)

                if response.status_code == 200:
                    data = response.json()
                    disease = data.get("disease", "Unknown")
                    confidence = float(data.get("confidence", 0.0))
                    is_uncertain = data.get("is_uncertain", False)
                    treatment = data.get("treatment", {})
                    probabilities = data.get("probabilities", {})
                    heatmap_b64 = data.get("heatmap")

                    if is_uncertain:
                        st.warning("⚠️ **Low Confidence Diagnostic Flag (<65%)**: Specimen prediction is inconclusive. Please retake the leaf photograph under even lighting.")

                    st.markdown(f"### Pathology: **{disease}**")
                    st.metric("Model Confidence", f"{confidence:.2f}%")

                    if heatmap_b64:
                        st.markdown("#### 🎯 Grad-CAM Lesion Localization Overlay")
                        heatmap_bytes = base64.b64decode(heatmap_b64)
                        st.image(Image.open(io.BytesIO(heatmap_bytes)), use_container_width=True)

                    if probabilities:
                        st.markdown("#### 📊 Prediction Probability Distribution")
                        df_probs = [{"Class": k.replace("_", " ").title(), "Probability (%)": v} for k, v in probabilities.items()]
                        fig = px.bar(df_probs, x="Probability (%)", y="Class", orientation="h", text="Probability (%)")
                        fig.update_layout(height=180, margin=dict(l=10, r=10, t=10, b=10))
                        st.plotly_chart(fig, use_container_width=True)

                    st.markdown("#### 📋 Remediation Protocol")
                    st.write(f"**🧪 Chemical:** {treatment.get('chemical', 'N/A')}")
                    st.write(f"**🌱 Organic:** {treatment.get('organic', 'N/A')}")
                    st.write(f"**🛡️ Prevention:** {treatment.get('prevention', 'N/A')}")

                    raw_heatmap = base64.b64decode(heatmap_b64) if heatmap_b64 else None
                    pdf_buffer = generate_pdf_report(disease, confidence, treatment, img_bytes, raw_heatmap)
                    st.download_button(
                        label="📥 Download Diagnostic PDF Report",
                        data=pdf_buffer,
                        file_name=f"Pathology_Report_{disease.replace(' ', '_')}.pdf",
                        mime="application/pdf"
                    )
                else:
                    st.error(f"API Error: {response.text}")
            except Exception as e:
                st.error(f"Failed to connect to API backend: {e}")